### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by cwilso6** [kroemerlab/ColocalizR#3]
> # For R versions >= 3.5
> if (!requireNamespace("BiocManager", quietly = TRUE))
+     install.packages("BiocManager")
Bioconductor version 3.12 (BiocManager 1.30.12), ?BiocManager::install for help
> BiocManager::install(c("EBImage","flowCore","S4Vectors"), version = "3.8")
Error: Bioconductor version '3.8' requires R version '3.5'; use `BiocManager::install(version = '3.12')`
  with R version 4.0; see https://bioconductor.org/install
> 
> devtools::install_github(c("kroemerlab/MetaxpR", "kroemerlab/MorphR", "kroemerlab/ColocalizR")

Restarting R session...

> install.packages(pkgs = c("rJava", "devtools"), repos = "http://cloud.r-project.org")
also installing the dependency ‘pkgload’

trying URL 'http://cloud.r-project.org/bin/macosx/contrib/4.0/pkgload_1.2.1.tgz'
Content type 'application/x-gzip' length 152333 bytes (148 KB)
==================================================
downloaded 148 KB

trying URL 'http://cloud.r-project.org/bin/macosx/contrib/4.0/rJava_0.9-13.tgz'
Content type 'application/x-gzip' length 756445 bytes (738 KB)
==================================================
downloaded 738 KB

trying URL 'http://cloud.r-project.org/bin/macosx/contrib/4.0/devtools_2.4.0.tgz'
Content type 'application/x-gzip' length 392413 bytes (383 KB)
==================================================
downloaded 383 KB

The downloaded binary packages are in
	/var/folders/h4/ffr701pj76v3yfk3mv8qfgp0001hcr/T//RtmpDoPSn6/downloaded_packages
> library(ColocalizR);Launcher()
Warning messages:
1: replacing previous import ‘Biobase::channel’ by ‘EBImage::channel’ when loading ‘MetaxpR’ 
2: replacing previous import ‘EBImage::normalize’ by ‘flowCore::normalize’ when loading ‘MetaxpR’ 
3: replacing previous import ‘EBImage::normalize’ by ‘flowCore::normalize’ when loading ‘ColocalizR’ 
Loading required package: shiny

Listening on http://127.0.0.1:6240
Warning: Error in : shinyjs: extendShinyjs: `functions` argument must be provided.
  78: stop
  77: errMsg
  76: shinyjs::extendShinyjs
Warning: Error in : shinyjs: extendShinyjs: `functions` argument must be provided.
  78: stop
  77: errMsg
  76: shinyjs::extendShinyjs

**Comment by annaschoonen** [comment]
Hi, trying to use ColocalizR on R version 4.1.0. I got all of the packages to load, but now when I try to launch it I get an error. 

This is the code given in the user manual:
> require(ColocalizR)
> Launcher()

This is the error I get: 
Listening on http://127.0.0.1:4120
Warning: Error in : shinyjs: extendShinyjs: `functions` argument must be provided.
  78: stop
  77: errMsg
  76: shinyjs::extendShinyjs

It is the same thing the person above is having issues with I think. Please let me know if anyone has figured this out because I would really like to use this program!

**Comment by asauvat** [comment]
Thanks for notifying, I was indeed able to reproduce the error on an updated system, and corrected the compatibility issue.
